Repository lexesjan/typescript-aniskip-extension, pull requests merged in 2021-07, with the labels that each got.

#65 Add Animixplay plyr url
  package.json
  src/players/plyr/metadata.json
Labels: enhancement

#66 Add player domains
  src/pages/gogoanime/metadata.json
  src/players/doodstream/metadata.json
  src/players/jw/metadata.json
  src/players/player_factory.ts
Labels: enhancement

#68 Add Discord links to README.md
  README.md
Labels: documentation

#70 Add API caching
  package.json
  src/options/components/SettingsPage/SettingsPage.tsx
  src/pages/base_page.ts
  src/scripts/background/script.ts
  src/scripts/background/types.ts
  src/utils/time.ts
Labels: enhancement

#72 Fix auto update of yarn version
  .github/workflows/ci.yml
Labels: bug
