Repository lexesjan/typescript-aniskip-extension, pull requests merged in 2022-03, with the labels that each got.

#256 Add new domain
  package.json
  src/components/SkipButtonContainer/SkipButtonContainer.tsx
  src/pages/animego/animego.ts
  src/pages/animego/index.ts
  src/pages/animego/metadata.json
  src/pages/page-factory.ts
  src/players/videojs/metadata.json
  src/players/videojs/styles.scss
Labels: bug, enhancement

#257 Add new player for animego page
  .eslintrc.js
  package.json
  src/components/SkipButtonContainer/SkipButtonContainer.tsx
  src/players/flowplayer/flowplayer.ts
  src/players/flowplayer/index.ts
  src/players/flowplayer/metadata.json
  src/players/flowplayer/styles.scss
  src/players/jw/metadata.json
  src/players/jw/styles.scss
  src/players/player-factory.ts
  src/players/styles.scss
Labels: enhancement

#283 Update page and player domains
  package.json
  src/pages/animepahe/metadata.json
  src/pages/gogoanime/metadata.json
  src/players/crunchyroll/crunchyroll.ts
  src/players/crunchyroll/metadata.json
  src/players/jw/metadata.json
  src/players/jw/styles.scss
Labels: website not longer work/update
