Repository lexesjan/typescript-aniskip-extension, pull requests merged in 2022-01, with the labels that each got.

#95 Add changelog notification
  package.json
  src/api/anilist-http-client/anilist-http-client.ts
  src/api/aniskip-http-client/aniskip-http-client.ts
  src/api/base-http-client/base-http-client.ts
  src/api/base-http-client/base-http-client.types.ts
  src/api/malsync-http-client/malsync-http-client.ts
  src/components/Searchbox/index.ts
  src/components/SkipButton/SkipButton.tsx
  src/components/SkipButtonContainer/SkipButtonContainer.tsx
  src/components/SubmitMenu/SubmitMenu.tsx
  src/components/index.ts
  src/data/settings/slice.ts
  src/data/settings/types.ts
  src/options/App.tsx
  src/options/components/ChangelogNotification/ChangelogNotification.tsx
  src/options/components/ChangelogNotification/index.ts
  src/options/components/SettingsPage/SettingsPage.tsx
  src/options/components/index.ts
  src/scripts/background/script.ts
  src/scripts/background/types.ts
  web-ext.config.js
  webpack/manifest.js
  yarn.lock
Labels: bug, enhancement

#100 Fix auto skip bugs
  .github/renovate.json
  package.json
  src/components/SkipButtonContainer/SkipButtonContainer.tsx
  src/players/base-player.ts
Labels: bug

#101 Fix changelog notification
  package.json
  src/scripts/background/script.ts
Labels: bug

#114 Add player control keybinds
  package.json
  src/api/aniskip-http-client/aniskip-http-client.ts
  src/api/aniskip-http-client/aniskip-http-client.types.ts
  src/components/SkipButtonContainer/SkipButtonContainer.tsx
  src/components/SkipTimeIndicatorContainer/SkipTimeIndicatorContainer.tsx
  src/components/SubmitMenu/SubmitMenu.tsx
  src/components/VoteMenu/VoteMenu.tsx
  src/data/player/slice.ts
  src/data/player/types.ts
  src/data/settings/slice.ts
  src/data/settings/types.ts
  src/options/components/SettingsPage/SettingsPage.tsx
  src/pages/base-page.ts
  src/pages/page-factory.ts
  src/pages/zoro/index.ts
  src/pages/zoro/metadata.json
  src/pages/zoro/zoro.ts
  src/pages/zoro/zoro.types.ts
  src/players/base-player.ts
  src/players/base-player.types.ts
  src/players/jw/jw.ts
  src/players/jw/metadata.json
  src/players/plyr/metadata.json
  src/players/plyr/plyr.ts
  src/scripts/background/types.ts
  src/utils/index.ts
  src/utils/time.ts
  web-ext.config.js
Labels: enhancement

#123 Add auto merging
  .github/renovate.json
Labels: enhancement, automated update

#125 Fix zoro titles
  package.json
  src/components/SkipButton/SkipButton.tsx
  src/components/SubmitMenu/SubmitMenu.tsx
  src/pages/zoro/zoro.ts
  yarn.lock
Labels: bug, enhancement

#127 Issue template
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/issue_report.yaml
  .github/assets/feature_request_concept_art_example.png
  .github/assets/issue_template_OS_version.png
  .github/assets/issue_template_browser_version.png
  .github/assets/issue_template_extension_version.png
  .github/assets/issue_template_extension_version_chrome.png
  .github/assets/issue_template_issue_example.png
  .github/assets/issue_template_thanks.png
  public/icon_128.ico
Labels: documentation, enhancement

#130 Add skip preview behaviour option
  package.json
  src/components/AnimeSearchModal/AnimeSearchModal.tsx
  src/components/Keyboard/Keyboard.tsx
  src/components/Keyboard/Keyboard.types.ts
  src/components/Keyboard/Keyboard.types.tsx
  src/components/SubmitMenu/SubmitMenu.tsx
  src/components/Toggle/Toggle.tsx
  src/components/Toggle/Toggle.types.ts
  src/components/Toggle/index.ts
  src/components/index.ts
  src/data/settings/slice.ts
  src/options/components/SettingsPage/SettingsPage.tsx
  src/players/jw/metadata.json
  src/players/plyr/metadata.json
  src/scripts/background/types.ts
Labels: enhancement

#135 Add Crunchyroll beta support
  package.json
  src/api/anilist-http-client/anilist-http-client.ts
  src/api/aniskip-http-client/aniskip-http-client.ts
  src/api/base-http-client/base-http-client.ts
  src/api/base-http-client/base-http-client.types.ts
  src/api/crunchyroll-beta-http-client/crunchyroll-beta-http-client.ts
  src/api/crunchyroll-beta-http-client/crunchyroll-beta-http-client.types.ts
  src/api/crunchyroll-beta-http-client/index.ts
  src/api/index.ts
  src/api/malsync-http-client/malsync-http-client.ts
  src/components/Overlay/Overlay.tsx
  src/data/page/slice.ts
  src/data/player/slice.ts
  src/options/components/ColourPicker/index.ts
  src/options/components/SettingsPage/SettingsPage.tsx
  src/options/components/index.ts
  src/pages/animepahe/animepahe.ts
  src/pages/animixplay/animixplay.ts
  src/pages/aniwatch/aniwatch.ts
  src/pages/aniwatch/index.ts
  src/pages/aniwatch/metadata.json
  src/pages/crunchyroll-beta/crunchyroll-beta.ts
  src/pages/crunchyroll-beta/index.ts
  src/pages/crunchyroll-beta/metadata.json
  src/pages/crunchyroll/crunchyroll.ts
  src/pages/fouranime/fouranime.ts
  src/pages/fouranime/index.ts
  src/pages/fouranime/metadata.json
  src/pages/page-factory.ts
  src/pages/zoro/zoro.ts
  src/players/base-player.ts
  src/players/base-player.types.ts
  src/players/crunchyroll/crunchyroll.ts
  src/players/crunchyroll/metadata.json
  src/players/doodstream/doodstream.ts
  src/players/doodstream/index.ts
  src/players/doodstream/metadata.json
  src/players/jw/jw.ts
  src/players/jw/metadata.json
  src/players/player-factory.ts
  src/players/plyr/metadata.json
  src/players/plyr/plyr.ts
  src/players/twistmoe/metadata.json
  src/players/twistmoe/twistmoe.ts
  src/players/videojs/fouranime.ts
  src/players/videojs/index.ts
  src/players/videojs/metadata.json
  src/players/videojs/videojs.ts
  src/scripts/background/script.ts
  src/scripts/background/types.ts
  src/scripts/content/script.ts
  src/scripts/player/styles.scss
  src/scripts/window-proxy/script.ts
  src/utils/window.ts
  webpack/manifest.js
  webpack/webpack.common.config.js
  webpack/webpack.dev.config.js
Labels: enhancement

#154 Change player button styles
  package.json
  src/components/MenuContainer/MenuContainer.tsx
  src/components/PlayerButton/PlayerButton.tsx
  src/components/PlayerButton/PlayerButton.types.ts
  src/components/PlayerButton/index.ts
  src/components/PlayerButtons/PlayerButtons.tsx
  src/components/SkipButton/SkipButton.tsx
  src/components/SubmitMenuButton/SubmitMenuButton.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/Tooltip.types.ts
  src/components/Tooltip/index.ts
  src/components/VoteMenuButton/VoteMenuButton.tsx
  src/components/VoteMenuButton/VoteMenuButton.types.ts
  src/components/index.ts
  src/players/base-player.ts
  src/players/common-styles.scss
  src/players/crunchyroll/styles.scss
  src/players/jw/styles.scss
  src/players/plyr/metadata.json
  src/players/plyr/styles.scss
  src/players/styles.scss
  src/players/twistmoe/styles.scss
  src/players/videojs/styles.scss
  src/renderers/base-renderer.ts
  src/scripts/player/styles.scss
Labels: enhancement

#163 Fix mobile styles
  package.json
  src/components/MenuContainer/MenuContainer.tsx
  src/components/SkipButton/SkipButton.tsx
  src/players/crunchyroll/crunchyroll.ts
  src/players/crunchyroll/styles.scss
  src/players/jw/styles.scss
  src/players/plyr/styles.scss
  src/players/styles.scss
  src/players/videojs/styles.scss
  src/utils/responsive.ts
  yarn.lock
Labels: bug
